/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

import dao.ThongKeBD_DAO;
import entity.ThongKe;

/**
 *
 * @author PC PHAN TRONG
 */
public class FrameNhanVien extends javax.swing.JInternalFrame implements ActionListener{
	ThongKeBD_DAO tk_dao =new ThongKeBD_DAO();
	 int nam =0;
	 int quy =0 ;
	private DefaultCategoryDataset dataset;
	private ChartPanel chartPanel;
    /**
     * Creates new form FrameNhanVien
     */
    public FrameNhanVien() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
       
        List<ThongKe> ds = tk_dao.getBLNV(Integer.parseInt(cboNam.getSelectedItem().toString()));
        nam = Integer.parseInt(cboNam.getSelectedItem().toString());
        quy = cboQuy.getSelectedIndex();
        List<ThongKe> dslct = tk_dao.getTNKNV(Integer.parseInt(cboNam.getSelectedItem().toString()));
        
//      System.out.println(tach(ds.get(0).getTongluong()));
      double tongluong =0;
      double tnk = 0;
      if(ds!=null)
      {	
      	dataset = new DefaultCategoryDataset();
      	String thang = null;
      	String thangct;
      	for(int i = 0; i< ds.size();i++)
          {
      		thang = String.valueOf(ds.get(i).getThang());
          	dataset.addValue(ds.get(i).getTongluong(), "Lương đã trả",thang);
          	tongluong+= ds.get(i).getTongluong();
          }
      	for(int j = 0 ; j< dslct.size();j++)
      	{
      		thangct = String.valueOf(dslct.get(j).getThang());
      		dataset.addValue(dslct.get(j).getTongluong(), "Thu nhập khác",thangct);
      		tnk+=dslct.get(j).getTongluong();
      	}
      	if(dslct.size()==0)
      	{
      		dataset.addValue(0.001, "Lương chưa trả",thang);
      	}
      	JFreeChart chart = ChartFactory.createBarChart("","Tháng","Tổng lương",dataset );
//      	chart.addLegend("");
      	
      	
      	chartPanel = new ChartPanel(chart);
      	
      	pnDaTinhCN.removeAll();
//      	pnDaTinhCN.setPreferredSize(new Dimension(100, 500));
      	pnDaTinhCN.setLayout(new CardLayout());
      	pnDaTinhCN.add(chartPanel);
      	
//      	pnDaTinhCN.validate();
//      	pnDaTinhCN.repaint();
      	lblTongLuong.setText (tach(tongluong));
      	lblThuNhapKhac.setText(tach(tnk));
      }
      cboNam.addActionListener(this);
      cboQuy.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnDaTinhCN = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboNam = new javax.swing.JComboBox<>();
        cboQuy = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblTongLuong = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblThuNhapKhac = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnLamMoi = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1334, 635));
        setPreferredSize(new java.awt.Dimension(1334, 635));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(846, 60));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhân viên");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(493, 493, 493)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(120, 162, 252));

        pnDaTinhCN.setBackground(new java.awt.Color(255, 255, 255));
        pnDaTinhCN.setPreferredSize(new java.awt.Dimension(0, 233));

        javax.swing.GroupLayout pnDaTinhCNLayout = new javax.swing.GroupLayout(pnDaTinhCN);
        pnDaTinhCN.setLayout(pnDaTinhCNLayout);
        pnDaTinhCNLayout.setHorizontalGroup(
            pnDaTinhCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnDaTinhCNLayout.setVerticalGroup(
            pnDaTinhCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo for Design Form/Filter.png"))); // NOI18N
        jLabel3.setText("Bộ lọc");

        cboNam.setBackground(new java.awt.Color(240, 240, 240));
        cboNam.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cboNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018" }));

        cboQuy.setBackground(new java.awt.Color(240, 240, 240));
        cboQuy.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cboQuy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Quý 1", "Quý 2", "Quý 3", "Quý 4" }));
       

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Tổng lương:");

        lblTongLuong.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTongLuong.setText("lblTongLuong");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Thu nhập khác:");

        lblThuNhapKhac.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblThuNhapKhac.setText("lblTNK");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cboQuy, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThuNhapKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboQuy)
                                .addComponent(cboNam, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblThuNhapKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btnLamMoi.setBackground(new java.awt.Color(0, 204, 204));
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo for Design Form/Refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDaTinhCN, javax.swing.GroupLayout.DEFAULT_SIZE, 1312, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnDaTinhCN, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1322, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
    	cboNam.setSelectedIndex(0);
    	cboQuy.setSelectedIndex(0);
    }//GEN-LAST:event_btnLamMoiActionPerformed
    
    public String tach(double luong)
    {
    	int chucnghin,tramnghin,trieu,nghin,tram,chuc,dvi, ty;
    	
        trieu=(int)  (luong/1000000);
        tramnghin =  (int)((luong-(trieu*1000000))/100000);
        chucnghin= (int) ((luong-(trieu*1000000)-(tramnghin*100000))/10000);
        nghin = (int)((luong - (trieu*1000000)-(tramnghin*100000) - (chucnghin*10000))/1000);
        tram =(int) ((luong - (trieu*1000000)-(tramnghin*100000) - (chucnghin*10000) - (nghin*1000))/100);
        chuc = (int)((luong - (trieu*1000000)-(tramnghin*100000) - (chucnghin*10000) - (nghin*1000) - (tram*100))/10);
        dvi = (int)((luong - (trieu*1000000)-(tramnghin*100000) - (chucnghin*10000) - (nghin*1000) - (tram*100)-(chuc *10)));
        
        if(trieu>0&&trieu<1000)
        {
        return (""+trieu+"."+tramnghin+""+chucnghin+""+nghin+"."+tram+""+chuc+""+dvi);
        }
        else if(trieu>=1000)
        {
        	ty = trieu/1000;
        	trieu = trieu-( ty*1000);
        	return (ty+"."+trieu+"."+tramnghin+""+chucnghin+""+nghin+"."+tram+""+chuc+""+dvi);
        }
        else if(trieu==0 && tramnghin>0)
        {
           return(""+tramnghin+chucnghin+nghin+"."+tram+chuc+dvi); 
        }
        else if(trieu==0 && tramnghin == 0 && chucnghin >0)
        {
        	return (""+chucnghin+nghin+"."+tram+chuc+dvi);
        }
        else if(trieu==0 && tramnghin == 0 && chucnghin == 0 && nghin >0)
        {
        	return(""+nghin+"."+tram+chuc+dvi);
        }
        else if(trieu==0 && tramnghin == 0 && chucnghin == 0 && nghin == 0 &&  tram>0)
        {
        	return(""+tram+chuc+dvi);
        }
        else if(trieu==0 && tramnghin == 0 && chucnghin == 0 && nghin == 0 && tram == 0 &&  chuc > 0)
        {
        	return(""+chuc+dvi);
        }
        else
        {
        	return(""+dvi);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JComboBox<String> cboQuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblThuNhapKhac;
    private javax.swing.JLabel lblTongLuong;
    private javax.swing.JPanel pnDaTinhCN;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		Object obj = e.getSource();
		if(obj.equals(cboNam))
		{
			if(Integer.parseInt(cboNam.getSelectedItem().toString())==nam)
			{
				
			}
			else
			{
				nam = Integer.parseInt(cboNam.getSelectedItem().toString());
				List<ThongKe> ds = tk_dao.getBLNV(Integer.parseInt(cboNam.getSelectedItem().toString()));
				List<ThongKe> dslct = tk_dao.getTNKNV(Integer.parseInt(cboNam.getSelectedItem().toString()));
				double tongluong =0;
				double tnk = 0 ;
				
			      if(ds.size()>0)
			      {	
			      	dataset = new DefaultCategoryDataset();
			      	String thang = null;
			      	String thangct;
			      	for(int i = 0; i< ds.size();i++)
			          {
			      		thang = String.valueOf(ds.get(i).getThang());
			          	dataset.addValue(ds.get(i).getTongluong(), "Lương công nhân",thang);
			          		          	
			          	tongluong+= ds.get(i).getTongluong();
			          }
			      	for(int j = 0 ; j< dslct.size();j++)
			      	{
			      		thangct = String.valueOf(dslct.get(j).getThang());
			      		dataset.addValue(dslct.get(j).getTongluong(), "Thu nhập khác",thangct);
			      		tnk+=dslct.get(j).getTongluong();
			      	}
			      	if(dslct.size()==0)
			      	{
			      		dataset.addValue(0.001, "Lương chưa trả",thang);
			      	}
			      	JFreeChart chart = ChartFactory.createBarChart("","Tháng","Thu nhập khác",dataset );
//			      	chart.addLegend("");
			      	pnDaTinhCN.removeAll();
			      	
			      	chartPanel = new ChartPanel(chart);
			      	
//			      	pnDaTinhCN.removeAll();
//			      	pnDaTinhCN.setPreferredSize(new Dimension(100, 500));
			      	pnDaTinhCN.setLayout(new CardLayout());
			      	pnDaTinhCN.add(chartPanel);
			      	
//			      	pnDaTinhCN.validate();
//			      	pnDaTinhCN.repaint();
			      	lblTongLuong.setText (tach(tongluong));
			      	lblThuNhapKhac.setText (tach(tnk));
			      	cboQuy.setSelectedIndex(0);
			      }
			      else
			      {
			    	  
			      }
			}
			
		
		}
		
	if(obj.equals(cboQuy))
	{
		if(cboQuy.getSelectedIndex()==quy)
		{
			
		}
		else
		{
			quy = cboQuy.getSelectedIndex();
			List<ThongKe> ds = tk_dao.getLuongNVTheoQuy(Integer.parseInt(cboNam.getSelectedItem().toString()), quy);
			List<ThongKe> dslct = tk_dao.getTNKNVTheoQuy(Integer.parseInt(cboNam.getSelectedItem().toString()), quy);
			double tongluong =0;
			double tnk = 0 ;
		      if(ds.size()>0)
		      {	
		      	dataset = new DefaultCategoryDataset();
		      	String thang = null;
		      	String thangct;
		      	for(int i = 0; i< ds.size();i++)
		          {
		      		thang = String.valueOf(ds.get(i).getThang());
		          	dataset.addValue(ds.get(i).getTongluong(), "Lương công nhân",thang);
		          		          	
		          	tongluong+= ds.get(i).getTongluong();
		          }
		      	for(int j = 0 ; j< dslct.size();j++)
		      	{
		      		thangct = String.valueOf(dslct.get(j).getThang());
		      		dataset.addValue(dslct.get(j).getTongluong(), "Thu nhập khác",thangct);
		      		tnk+=dslct.get(j).getTongluong();
		      	}
		      	if(dslct.size()==0)
		      	{
		      		dataset.addValue(0.001, "Thu nhập khác",thang);
		      	}
		      	JFreeChart chart = ChartFactory.createBarChart("","Tháng","Tổng lương",dataset );
//		      	chart.addLegend("");
		      	pnDaTinhCN.remove(chartPanel);
		      	
		      	chartPanel = new ChartPanel(chart);
		      	
//		      	pnDaTinhCN.removeAll();
//		      	pnDaTinhCN.setPreferredSize(new Dimension(100, 500));
		      	pnDaTinhCN.setLayout(new CardLayout());
		      	pnDaTinhCN.add(chartPanel);
		      	
//		      	pnDaTinhCN.validate();
//		      	pnDaTinhCN.repaint();
		      	lblTongLuong.setText (tach(tongluong));
		      	lblThuNhapKhac.setText (tach(tnk));
		      }
		}
		
		
		
	}
	}
}
