/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;

import connect.Connect;
import dao.ChamCongNVHC_DAO;
import dao.CongDoan_DAO;
import dao.DuLieuCongNhan_DAO;
import dao.NhanVien_DAO;
import dao.ThuNhapKhac_DAO;
import entity.ChamCongNVHC;
import entity.CongDoan;
import entity.NhanVien;
import entity.NhanVien_CongDoan;
import entity.SanPham;
import entity.ThuNhapKhac;

/**
 *
 * @author PC PHAN TRONG
 */
public class ImprotDataNhanVien_GUI extends javax.swing.JFrame {

    private String fileName;
    private Connection con = new Connect().getConnect();
    private NhanVien_DAO nvDao = new NhanVien_DAO();
	private ThuNhapKhac_DAO tnkDao = new ThuNhapKhac_DAO();
	private DuLieuCongNhan_DAO cnDao = new DuLieuCongNhan_DAO();
	private CongDoan_DAO cdDao = new CongDoan_DAO();
	private ChamCongNVHC_DAO dlieu = new ChamCongNVHC_DAO();
    public ImprotDataNhanVien_GUI() {
        initComponents();
        setLocationRelativeTo(null);
//      setSize(500,400);
      setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBrowse = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();

       
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("File Path");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(322, 330, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTextField1)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBrowse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo for Design Form/icons8-browse-folder-64_1.png"))); // NOI18N
        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo for Design Form/Cancel.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnUpload.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo for Design Form/Upload.png"))); // NOI18N
        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {
    	String currentDicrectoryPath = "Desktop";
		JFileChooser excelFileChooserImport = new JFileChooser();
		FileFilter filter = new FileNameExtensionFilter("files","csv","xls","txt");
		excelFileChooserImport.setFileFilter(filter);
		excelFileChooserImport.showOpenDialog(null);
		File f = excelFileChooserImport.getSelectedFile();
//		FileInputStream fis=new FileInputStream(f);
//		InputStreamReader isr=new InputStreamReader(fis, "UTF-8");
		fileName = f.getAbsolutePath();
		jTextField1.setText(fileName);
    }

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
    	String path = jTextField1.getText();
    	if(path.trim().equals("")) {
    		JOptionPane.showMessageDialog(null, "Vui lòng chọn đường dẫn");
    		jTextField1.requestFocus();
    	}
    	else {
    		FileReader fr = null;
    		try {
    			fr = new FileReader(path);
    		} catch (FileNotFoundException e) {
    			e.printStackTrace();
    		}
            BufferedReader br = new BufferedReader(fr);
            String i;
            try {
    			while ((i = br.readLine()) !=null) {
    			    String[] data = i.split(",");
    			    				String ma = taoMaNhanVienHanhChinh();
    								NhanVien nv = nvDao.getNVtheoma(data[0]);
    								
    								int thang = Integer.parseInt(data[1]);
    								int nam = Integer.parseInt(data[2]);
    								double heSoLuong = Double.parseDouble(data[3]);
    								int congNgayLe = Integer.parseInt(data[4]);
    								int congNgayThuong = Integer.parseInt(data[5]);
    								int nghiKhongPhep = Integer.parseInt(data[6]);
    								int soCongChuan = 2 * congNgayLe + congNgayThuong - nghiKhongPhep;

    								String maThuNhapKhac = taoMaThuNhapKhac();
    								double luongLamThem = Double.parseDouble(data[7]);
    								double phuCap = Double.parseDouble(data[8]);
    								double thuong = Double.parseDouble(data[9]);

    								double thuNhapKhac = luongLamThem + phuCap + thuong;
    								ChamCongNVHC nvien = new ChamCongNVHC(ma, nv, heSoLuong, congNgayLe, congNgayThuong,
    										nghiKhongPhep, thang , nam);
    								ThuNhapKhac tnhap = new ThuNhapKhac(maThuNhapKhac, luongLamThem, phuCap, thuong, nv,
    										thang , nam);
    								
    								if(dlieu.themChamCongNhanVienHC(nvien) && dlieu.themThuNhapKhac(tnhap) ) {
    									DuLieuTinhLuong_GUI.dataNhanVien.addRow(new Object[] { nv.getMaNV(), nv.getTenNV(), tach(heSoLuong), nghiKhongPhep,
    											congNgayLe, congNgayThuong, soCongChuan, thang, nam, tach(thuNhapKhac) });
    								}
    			}
//    			JOptionPane.showMessageDialog(null, "Thành công");
    			setVisible(false);
    		} catch (IOException e) {
    			// TODO Auto-generated catch block
    			e.printStackTrace();
    		}
            try {
    			br.close();
    		} catch (IOException e) {
    			// TODO Auto-generated catch block
    			e.printStackTrace();
    		}
            try {
    			fr.close();
    		} catch (IOException e) {
    			// TODO Auto-generated catch block
    			e.printStackTrace();
    		}
    	}
    	
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        int lick=JOptionPane.showConfirmDialog(null,"Bạn Có Muốn Thoát Hay Không?","Thông Báo",2);
        if(lick==JOptionPane.OK_OPTION){
        		this.setVisible(false);
        }
        else{
            if(lick==JOptionPane.CANCEL_OPTION){    
                this.setVisible(true);
            }
        }
    }
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprotDataNhanVien_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprotDataNhanVien_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprotDataNhanVien_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprotDataNhanVien_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprotDataNhanVien_GUI().setVisible(true);
            }
        });
    }
    public String taoMaNhanVienHanhChinh() {

 		String maCuoi = dlieu.getNVCuoi().getMaChamCong();
 		long so = Long.parseLong(maCuoi.substring(2)) + 100000 + 1;
 		String soMoi = ("" + so).substring(1);
 		return "CC" + soMoi;
 	}
	public String taoMaThuNhapKhac() {

 		String maCuoi = dlieu.getTHCuoi().getMaThuNhapKhac();
 		long so = Long.parseLong(maCuoi.substring(2)) + 100000 + 1;
 		String soMoi = ("" + so).substring(1);
 		return "TN" + soMoi;
 	}
 	public String tach(double luong) {
 		int chucnghin, tramnghin, trieu, nghin, tram, chuc, dvi;
 		trieu = (int) (luong / 1000000);
 		tramnghin = (int) ((luong - (trieu * 1000000)) / 100000);
 		chucnghin = (int) ((luong - (trieu * 1000000) - (tramnghin * 100000)) / 10000);
 		nghin = (int) ((luong - (trieu * 1000000) - (tramnghin * 100000) - (chucnghin * 10000)) / 1000);
 		tram = (int) ((luong - (trieu * 1000000) - (tramnghin * 100000) - (chucnghin * 10000) - (nghin * 1000)) / 100);
 		chuc = (int) ((luong - (trieu * 1000000) - (tramnghin * 100000) - (chucnghin * 10000) - (nghin * 1000)
 				- (tram * 100)) / 10);
 		dvi = (int) ((luong - (trieu * 1000000) - (tramnghin * 100000) - (chucnghin * 10000) - (nghin * 1000)
 				- (tram * 100) - (chuc * 10)));

 		if (trieu > 0) {
 			return ("" + trieu + "." + tramnghin + "" + chucnghin + "" + nghin + "." + tram + "" + chuc + "" + dvi);
 		} else if (trieu == 0 && tramnghin > 0) {
 			return ("" + tramnghin + chucnghin + nghin + "." + tram + chuc + dvi);
 		} else if (trieu == 0 && tramnghin == 0 && chucnghin > 0) {
 			return ("" + chucnghin + nghin + "." + tram + chuc + dvi);
 		} else if (trieu == 0 && tramnghin == 0 && chucnghin == 0 && nghin > 0) {
 			return ("" + nghin + "." + tram + chuc + dvi);
 		} else if (trieu == 0 && tramnghin == 0 && chucnghin == 0 && nghin == 0 && tram > 0) {
 			return ("" + tram + chuc + dvi);
 		} else if (trieu == 0 && tramnghin == 0 && chucnghin == 0 && nghin == 0 && tram == 0 && chuc > 0) {
 			return ("" + chuc + dvi);
 		} else {
 			return ("" + dvi);
 		}
 	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
